In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

Bunch -> dict 를 랩핑한것 (비슷하다 보면 됨)

In [3]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [4]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [6]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [7]:
log.fit(x_train, y_train)

LogisticRegression()

In [8]:
log.coef_, log.intercept_

(array([[-0.36861882,  0.88305582, -2.3316416 , -1.00571342],
        [ 0.43485688, -0.30465033, -0.13985713, -0.77093511],
        [-0.06623806, -0.57840549,  2.47149873,  1.77664853]]),
 array([  8.87660626,   2.06576766, -10.94237392]))

In [9]:
log.predict_proba(x_train[100:104])

array([[7.07580119e-03, 8.14540738e-01, 1.78383461e-01],
       [9.84645732e-01, 1.53542031e-02, 6.53002882e-08],
       [9.82547638e-01, 1.74522838e-02, 7.84341481e-08],
       [1.11858213e-05, 3.22183884e-02, 9.67770426e-01]])

In [10]:
log.predict(x_train[100:104])

array([1, 0, 0, 2])

In [11]:
from sklearn import metrics

In [12]:
y_pred = log.predict(x_train)
y_pred.shape

(112,)

In [13]:
y_train

array([0, 2, 2, 2, 1, 0, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 2, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 1, 2,
       2, 2, 2, 0, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2, 1, 2,
       2, 0, 1, 2, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 2, 1, 0, 2, 2,
       0, 2])

In [14]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      0.91      0.94        35
           2       0.93      0.97      0.95        39

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112



In [15]:
metrics.confusion_matrix(y_train, y_pred)

array([[38,  0,  0],
       [ 0, 32,  3],
       [ 0,  1, 38]], dtype=int64)